-- Sales Campaigns — a parallel entity to research_campaigns (identical shape),
-- surfaced under Pipeline and selectable on leads via a new "Sales Campaign"
-- source. Research Campaigns is left fully intact alongside this.

-- 1. The table (mirrors public.research_campaigns) ------------------------
CREATE TABLE IF NOT EXISTS public.sales_campaigns (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             text NOT NULL,
    segment          text,
    region_id        bigint REFERENCES public.regions(id)       ON DELETE SET NULL,
    service_major_id bigint REFERENCES public.service_major(id) ON DELETE SET NULL,
    status           text DEFAULT 'Active'::text NOT NULL,
    notes            text,
    owner_id         bigint REFERENCES public.people(id)        ON DELETE SET NULL,
    created_at       timestamp with time zone DEFAULT now() NOT NULL,
    created_by       bigint REFERENCES public.people(id)        ON DELETE SET NULL,
    CONSTRAINT sales_campaigns_status_check
      CHECK ((status = ANY (ARRAY['Active'::text, 'Paused'::text, 'Completed'::text, 'Abandoned'::text])))
);

-- Match the access pattern of research_campaigns (service role is used from the
-- Netlify functions; anon/authenticated kept consistent with sibling tables).
GRANT ALL ON TABLE public.sales_campaigns TO anon;
GRANT ALL ON TABLE public.sales_campaigns TO authenticated;
GRANT ALL ON TABLE public.sales_campaigns TO service_role;

-- 2. Lead linkage — new FK column on leads (research_campaign_id is untouched) -
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS sales_campaign_id bigint;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'leads_sales_campaign_id_fkey') THEN
    ALTER TABLE public.leads
      ADD CONSTRAINT leads_sales_campaign_id_fkey
      FOREIGN KEY (sales_campaign_id) REFERENCES public.sales_campaigns(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 3. New lead source so a lead can be attributed to a Sales Campaign ---------
INSERT INTO public.lead_sources (name)
SELECT 'Sales Campaign'
WHERE NOT EXISTS (SELECT 1 FROM public.lead_sources WHERE name = 'Sales Campaign');
