-- Campaign Cockpit — turns a research_campaign from a label into a managed
-- outbound effort. Adds mission targets/timeframe to the campaign, a pre-lead
-- "target list" backlog (campaign_targets), and an outreach cadence template
-- (campaign_cadence_steps). Nothing here touches the existing leads flow except
-- to let a promoted target spawn a lead (handled app-side, FK is the only link).

-- 1. Mission fields on research_campaigns ---------------------------------
--    Timeframe + the three pacing targets shown in the cockpit funnel strip.
ALTER TABLE public.research_campaigns
  ADD COLUMN IF NOT EXISTS start_date       date,
  ADD COLUMN IF NOT EXISTS end_date         date,
  ADD COLUMN IF NOT EXISTS target_accounts  integer,
  ADD COLUMN IF NOT EXISTS target_qualified integer,
  ADD COLUMN IF NOT EXISTS target_promoted  integer;

-- 2. campaign_targets — the researched-but-not-yet-worked backlog ----------
--    A target is researched (Researching) → made list-ready (Ready) → either
--    Promoted (spawns a lead carrying research_campaign_id) or Disqualified.
CREATE TABLE IF NOT EXISTS public.campaign_targets (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    research_campaign_id bigint NOT NULL REFERENCES public.research_campaigns(id) ON DELETE CASCADE,
    organisation_id      bigint REFERENCES public.organisations(id) ON DELETE SET NULL,
    company_name         text,
    contact_name         text,
    contact_role         text,
    contact_email        text,
    contact_phone        text,
    priority             text DEFAULT 'Warm'::text NOT NULL,
    research_notes       text,
    status               text DEFAULT 'Researching'::text NOT NULL,
    promoted_lead_id     bigint REFERENCES public.leads(id) ON DELETE SET NULL,
    promoted_at          timestamp with time zone,
    disqualify_reason    text,
    owner_id             bigint REFERENCES public.people(id) ON DELETE SET NULL,
    created_by           bigint REFERENCES public.people(id) ON DELETE SET NULL,
    created_at           timestamp with time zone DEFAULT now() NOT NULL,
    updated_at           timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT campaign_targets_priority_check
      CHECK ((priority = ANY (ARRAY['Hot'::text, 'Warm'::text, 'Cold'::text]))),
    CONSTRAINT campaign_targets_status_check
      CHECK ((status = ANY (ARRAY['Researching'::text, 'Ready'::text, 'Promoted'::text, 'Disqualified'::text])))
);

CREATE INDEX IF NOT EXISTS campaign_targets_campaign_idx
  ON public.campaign_targets (research_campaign_id);

GRANT ALL ON TABLE public.campaign_targets TO anon;
GRANT ALL ON TABLE public.campaign_targets TO authenticated;
GRANT ALL ON TABLE public.campaign_targets TO service_role;

-- 3. campaign_cadence_steps — the outreach sequence template ---------------
--    One row per planned touch. Per-lead progress is DERIVED app-side from the
--    lead's logged interactions against this template (no per-lead state row).
CREATE TABLE IF NOT EXISTS public.campaign_cadence_steps (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    research_campaign_id bigint NOT NULL REFERENCES public.research_campaigns(id) ON DELETE CASCADE,
    step_no              integer NOT NULL,
    day_offset           integer DEFAULT 0 NOT NULL,
    channel              text DEFAULT 'Email'::text NOT NULL,
    instruction          text,
    created_at           timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT campaign_cadence_steps_channel_check
      CHECK ((channel = ANY (ARRAY['Email'::text, 'Call'::text, 'LinkedIn'::text, 'Visit'::text, 'Other'::text])))
);

CREATE INDEX IF NOT EXISTS campaign_cadence_steps_campaign_idx
  ON public.campaign_cadence_steps (research_campaign_id);

GRANT ALL ON TABLE public.campaign_cadence_steps TO anon;
GRANT ALL ON TABLE public.campaign_cadence_steps TO authenticated;
GRANT ALL ON TABLE public.campaign_cadence_steps TO service_role;
