-- Branches above Regions.
-- Introduces a `branches` lookup that sits ABOVE the existing `regions`:
--   branches (1) → regions (N).
-- Records (deals/leads/orgs/campaigns) gain their own branch_id that auto-fills
-- from the region's branch but is overridable. Users can be scoped at either
-- level (system_user_regions stays; new system_user_branches added).
-- Idempotent — safe to re-run.

-- 1. branches lookup (mirrors public.regions) ------------------------------
CREATE TABLE IF NOT EXISTS public.branches (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL UNIQUE,
    active     boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by bigint REFERENCES public.people(id) ON DELETE SET NULL
);
GRANT ALL ON TABLE public.branches TO anon;
GRANT ALL ON TABLE public.branches TO authenticated;
GRANT ALL ON TABLE public.branches TO service_role;

-- 2. regions.branch_id — a region belongs to one branch -------------------
ALTER TABLE public.regions
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;

-- 3. branch_id on the records that already carry region_id ----------------
ALTER TABLE public.deals
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.organisations
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.research_campaigns
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;

-- 4. Branch-level user scoping (mirrors system_user_regions) --------------
CREATE TABLE IF NOT EXISTS public.system_user_branches (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_user_id bigint NOT NULL REFERENCES public.system_users(id) ON DELETE CASCADE,
    branch_id      bigint NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
    created_at     timestamp with time zone DEFAULT now() NOT NULL,
    created_by     bigint REFERENCES public.people(id),
    CONSTRAINT system_user_branches_user_branch_key UNIQUE (system_user_id, branch_id)
);
CREATE INDEX IF NOT EXISTS idx_system_user_branches_user
  ON public.system_user_branches USING btree (system_user_id);
GRANT ALL ON TABLE public.system_user_branches TO anon;
GRANT ALL ON TABLE public.system_user_branches TO authenticated;
GRANT ALL ON TABLE public.system_user_branches TO service_role;

-- 5. Seed branches + map current regions ----------------------------------
INSERT INTO public.branches (name)
SELECT 'Cape Town' WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE name = 'Cape Town');
INSERT INTO public.branches (name)
SELECT 'Centurion' WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE name = 'Centurion');

-- Western Cape → Cape Town, Inland → Centurion
UPDATE public.regions SET branch_id = (SELECT id FROM public.branches WHERE name = 'Cape Town')
  WHERE name = 'Western Cape';
UPDATE public.regions SET branch_id = (SELECT id FROM public.branches WHERE name = 'Centurion')
  WHERE name = 'Inland';

-- 6. Backfill record branch_id from each record's region (only where unset
--    so a re-run never clobbers a manual override).
UPDATE public.deals              d SET branch_id = r.branch_id FROM public.regions r WHERE d.region_id = r.id AND d.branch_id IS NULL;
UPDATE public.leads              l SET branch_id = r.branch_id FROM public.regions r WHERE l.region_id = r.id AND l.branch_id IS NULL;
UPDATE public.organisations      o SET branch_id = r.branch_id FROM public.regions r WHERE o.region_id = r.id AND o.branch_id IS NULL;
UPDATE public.research_campaigns c SET branch_id = r.branch_id FROM public.regions r WHERE c.region_id = r.id AND c.branch_id IS NULL;
UPDATE public.sales_campaigns    s SET branch_id = r.branch_id FROM public.regions r WHERE s.region_id = r.id AND s.branch_id IS NULL;
