-- ============================================================================
-- Increment A — Lead lifecycle foundations  (DEV ONLY — Production is frozen)
-- ----------------------------------------------------------------------------
-- PURELY ADDITIVE & IDEMPOTENT. Safe to run against the live Dev app: new
-- tables/columns are ignored by the current code until Increment B/C/D wire
-- them up.
--
-- NOTE: the server-side lead-status triggers are intentionally LEFT IN PLACE
-- here. They are retired in Increment B, at the same time the app-layer status
-- engine is deployed, so Dev never has a window with no status logic at all.
-- ============================================================================

BEGIN;

-- 1. Decline reasons lookup (Decline dropdown + free text) --------------------
CREATE TABLE IF NOT EXISTS public.decline_reasons (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    description text,
    active      boolean NOT NULL DEFAULT true,
    sort_order  integer NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON TABLE public.decline_reasons TO anon, authenticated, service_role;

INSERT INTO public.decline_reasons (name, sort_order)
SELECT v.name, v.so FROM (VALUES
    ('No budget',                 10),
    ('No current need',           20),
    ('Using a competitor',        30),
    ('Timing not right',          40),
    ('Unresponsive',              50),
    ('Out of our coverage area',  60),
    ('Other',                     90)
) AS v(name, so)
WHERE NOT EXISTS (SELECT 1 FROM public.decline_reasons d WHERE d.name = v.name);

-- 2. Qualification dimension descriptions (admin-editable; drive hover help) ---
--    key MUST match the leads score columns: fit / trigger_score / access / capacity
CREATE TABLE IF NOT EXISTS public.qualification_dimensions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key         text NOT NULL UNIQUE,
    label       text NOT NULL,
    description text,
    sort_order  integer NOT NULL DEFAULT 0,
    active      boolean NOT NULL DEFAULT true,
    updated_at  timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON TABLE public.qualification_dimensions TO anon, authenticated, service_role;

INSERT INTO public.qualification_dimensions (key, label, description, sort_order)
SELECT v.key, v.label, v.descr, v.so FROM (VALUES
    ('fit',           'Fit',      'Are they in your ideal client profile? (sector, size, region you serve)',          10),
    ('trigger_score', 'Trigger',  'Is there a reason now? (new site, incident, renewal coming up, change of FM)',     20),
    ('access',        'Access',   'Can you actually get in front of a decision-maker?',                               30),
    ('capacity',      'Capacity', 'Can you serve them if you win? (region coverage, manpower vs tech)',               40)
) AS v(key, label, descr, so)
WHERE NOT EXISTS (SELECT 1 FROM public.qualification_dimensions q WHERE q.key = v.key);

-- 3. Per-rating comments + lifecycle stamps + peer review on leads ------------
ALTER TABLE public.leads
    ADD COLUMN IF NOT EXISTS fit_comment         text,
    ADD COLUMN IF NOT EXISTS trigger_comment     text,
    ADD COLUMN IF NOT EXISTS access_comment      text,
    ADD COLUMN IF NOT EXISTS capacity_comment    text,
    ADD COLUMN IF NOT EXISTS working_eligible_at timestamptz,  -- when conds 1-3 first all met (waiting clock starts)
    ADD COLUMN IF NOT EXISTS working_at          timestamptz,  -- when it actually became Working
    ADD COLUMN IF NOT EXISTS qualified_at        timestamptz,
    ADD COLUMN IF NOT EXISTS decline_reason_id   bigint REFERENCES public.decline_reasons(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS peer_review_status  text,         -- NULL | Pending | Approved | Rejected
    ADD COLUMN IF NOT EXISTS peer_review_at      timestamptz,
    ADD COLUMN IF NOT EXISTS peer_review_by      bigint REFERENCES public.people(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS peer_review_note    text;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'leads_peer_review_status_check') THEN
    ALTER TABLE public.leads
      ADD CONSTRAINT leads_peer_review_status_check
      CHECK (peer_review_status IS NULL OR peer_review_status IN ('Pending','Approved','Rejected'));
  END IF;
END $$;

-- 4. Comment on the qualification junctions (justify each flag / decision) -----
ALTER TABLE public.lead_red_flags           ADD COLUMN IF NOT EXISTS comment text;
ALTER TABLE public.lead_strategic_decisions ADD COLUMN IF NOT EXISTS comment text;

-- 5. Multiple contacts per lead ------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lead_contacts (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id       bigint NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
    person_id     bigint REFERENCES public.people(id) ON DELETE SET NULL,
    contact_name  text,   -- free-text when the person is not yet in the DB (created on promote)
    contact_title text,
    contact_email text,
    contact_phone text,
    is_primary    boolean NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now(),
    created_by    bigint REFERENCES public.people(id) ON DELETE SET NULL
);
GRANT ALL ON TABLE public.lead_contacts TO anon, authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_lead_contacts_lead ON public.lead_contacts (lead_id);
-- at most one primary contact per lead
CREATE UNIQUE INDEX IF NOT EXISTS uq_lead_contacts_primary ON public.lead_contacts (lead_id) WHERE is_primary;

-- Backfill: existing lead's target person becomes its primary contact.
INSERT INTO public.lead_contacts (lead_id, person_id, contact_name, is_primary, created_by)
SELECT l.id, l.target_person_id, l.target_person_name, true, l.created_by
FROM public.leads l
WHERE (l.target_person_id IS NOT NULL OR l.target_person_name IS NOT NULL)
  AND NOT EXISTS (SELECT 1 FROM public.lead_contacts lc WHERE lc.lead_id = l.id);

-- 6. Description history (original retained at the bottom; new entries appended)
CREATE TABLE IF NOT EXISTS public.lead_description_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id     bigint NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
    body        text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    created_by  bigint REFERENCES public.people(id) ON DELETE SET NULL
);
GRANT ALL ON TABLE public.lead_description_log TO anon, authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_lead_description_log_lead ON public.lead_description_log (lead_id);

-- Backfill: seed each existing lead's current description as the first entry.
INSERT INTO public.lead_description_log (lead_id, body, created_at, created_by)
SELECT l.id, l.description, COALESCE(l.created_at, now()), l.created_by
FROM public.leads l
WHERE l.description IS NOT NULL AND btrim(l.description) <> ''
  AND NOT EXISTS (SELECT 1 FROM public.lead_description_log d WHERE d.lead_id = l.id);

-- 7. New-lead waiting period (minutes) — editable in Admin ----------------------
INSERT INTO public.settings (key, value)
SELECT 'new_lead_waiting_minutes', '10'
WHERE NOT EXISTS (SELECT 1 FROM public.settings WHERE key = 'new_lead_waiting_minutes');

COMMIT;
