-- ═══════════════════════════════════════════════════════════════════════
-- PROD SYNC → Focus v7.6.98   (prod was v7.6.61)
-- ═══════════════════════════════════════════════════════════════════════
-- Brings the PRODUCTION database up to the dev (test-branch) schema so the
-- v7.6.98 code can be deployed to prod. Additive only — no DROP/TRUNCATE/
-- DELETE of business data. Reviewed file-by-file; the same migrations were
-- already applied cleanly on the dev DB (a 2026-06-09 prod clone).
--
--   ⚠  TAKE A BACKUP FIRST (Supabase → Database → Backups, or pg_dump).
--   ▸  Run this WHOLE script in the Supabase SQL Editor against PRODUCTION.
--   ▸  Then deploy the code:  BRANCH=main node push_to_github.js
--
-- Order:
--   PART 1 — Core (required for v7.6.98 to load on prod)
--     1 administer_deals permission   2 campaign cockpit   3 branches
--     4 menu-section permissions       5 lead source options 6 lead cadence anchor
--   PART 2 — Quote tool (Proposal Builder tab; phase a → a_seed → b → b2 → b3)
--   PART 3 — Verification
-- ═══════════════════════════════════════════════════════════════════════


-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  PART 1 — CORE  (wrapped in one transaction; all idempotent)           ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
BEGIN;

-- ───────────────────────────────────────────── sql/add_administer_deals_permission.sql
-- Deal Administration page: edit secured deals + delete deals.
-- These actions are blocked on the normal Opportunities page; they are only
-- available on the dedicated, permission-gated Deal Administration page.
-- Apply to the TEST DB first:
--   ~/scoop/apps/postgresql/current/bin/psql.exe "$SUPABASE_TEST_DB_URL" -f sql/add_administer_deals_permission.sql
-- (Admins carry 'all' and reach the page regardless; this grants the explicit permission.)

insert into permissions (name, description)
values ('administer_deals', 'Deal Administration: edit secured deals and delete deals')
on conflict (name) do nothing;

-- Grant to the Admin role only (strictest default; widen later if needed).
insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
cross join permissions p
where r.name = 'Admin' and p.name = 'administer_deals'
on conflict (role_id, permission_id) do nothing;

-- ───────────────────────────────────────────── sql/add_campaign_cockpit.sql
-- Campaign Cockpit — turns a research_campaign from a label into a managed
-- outbound effort. Adds mission targets/timeframe to the campaign, a pre-lead
-- "target list" backlog (campaign_targets), and an outreach cadence template
-- (campaign_cadence_steps). Nothing here touches the existing leads flow except
-- to let a promoted target spawn a lead (handled app-side, FK is the only link).

-- 1. Mission fields on research_campaigns ---------------------------------
--    Timeframe + the three pacing targets shown in the cockpit funnel strip.
ALTER TABLE public.research_campaigns
  ADD COLUMN IF NOT EXISTS start_date       date,
  ADD COLUMN IF NOT EXISTS end_date         date,
  ADD COLUMN IF NOT EXISTS target_accounts  integer,
  ADD COLUMN IF NOT EXISTS target_qualified integer,
  ADD COLUMN IF NOT EXISTS target_promoted  integer;

-- 2. campaign_targets — the researched-but-not-yet-worked backlog ----------
--    A target is researched (Researching) → made list-ready (Ready) → either
--    Promoted (spawns a lead carrying research_campaign_id) or Disqualified.
CREATE TABLE IF NOT EXISTS public.campaign_targets (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    research_campaign_id bigint NOT NULL REFERENCES public.research_campaigns(id) ON DELETE CASCADE,
    organisation_id      bigint REFERENCES public.organisations(id) ON DELETE SET NULL,
    company_name         text,
    contact_name         text,
    contact_role         text,
    contact_email        text,
    contact_phone        text,
    priority             text DEFAULT 'Warm'::text NOT NULL,
    research_notes       text,
    status               text DEFAULT 'Researching'::text NOT NULL,
    promoted_lead_id     bigint REFERENCES public.leads(id) ON DELETE SET NULL,
    promoted_at          timestamp with time zone,
    disqualify_reason    text,
    owner_id             bigint REFERENCES public.people(id) ON DELETE SET NULL,
    created_by           bigint REFERENCES public.people(id) ON DELETE SET NULL,
    created_at           timestamp with time zone DEFAULT now() NOT NULL,
    updated_at           timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT campaign_targets_priority_check
      CHECK ((priority = ANY (ARRAY['Hot'::text, 'Warm'::text, 'Cold'::text]))),
    CONSTRAINT campaign_targets_status_check
      CHECK ((status = ANY (ARRAY['Researching'::text, 'Ready'::text, 'Promoted'::text, 'Disqualified'::text])))
);

CREATE INDEX IF NOT EXISTS campaign_targets_campaign_idx
  ON public.campaign_targets (research_campaign_id);

GRANT ALL ON TABLE public.campaign_targets TO anon;
GRANT ALL ON TABLE public.campaign_targets TO authenticated;
GRANT ALL ON TABLE public.campaign_targets TO service_role;

-- 3. campaign_cadence_steps — the outreach sequence template ---------------
--    One row per planned touch. Per-lead progress is DERIVED app-side from the
--    lead's logged interactions against this template (no per-lead state row).
CREATE TABLE IF NOT EXISTS public.campaign_cadence_steps (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    research_campaign_id bigint NOT NULL REFERENCES public.research_campaigns(id) ON DELETE CASCADE,
    step_no              integer NOT NULL,
    day_offset           integer DEFAULT 0 NOT NULL,
    channel              text DEFAULT 'Email'::text NOT NULL,
    instruction          text,
    created_at           timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT campaign_cadence_steps_channel_check
      CHECK ((channel = ANY (ARRAY['Email'::text, 'Call'::text, 'LinkedIn'::text, 'Visit'::text, 'Other'::text])))
);

CREATE INDEX IF NOT EXISTS campaign_cadence_steps_campaign_idx
  ON public.campaign_cadence_steps (research_campaign_id);

GRANT ALL ON TABLE public.campaign_cadence_steps TO anon;
GRANT ALL ON TABLE public.campaign_cadence_steps TO authenticated;
GRANT ALL ON TABLE public.campaign_cadence_steps TO service_role;

-- ───────────────────────────────────────────── sql/add_branches.sql
-- Branches above Regions.
-- Introduces a `branches` lookup that sits ABOVE the existing `regions`:
--   branches (1) → regions (N).
-- Records (deals/leads/orgs/campaigns) gain their own branch_id that auto-fills
-- from the region's branch but is overridable. Users can be scoped at either
-- level (system_user_regions stays; new system_user_branches added).
-- Idempotent — safe to re-run.

-- 1. branches lookup (mirrors public.regions) ------------------------------
CREATE TABLE IF NOT EXISTS public.branches (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL UNIQUE,
    active     boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by bigint REFERENCES public.people(id) ON DELETE SET NULL
);
GRANT ALL ON TABLE public.branches TO anon;
GRANT ALL ON TABLE public.branches TO authenticated;
GRANT ALL ON TABLE public.branches TO service_role;

-- 2. regions.branch_id — a region belongs to one branch -------------------
ALTER TABLE public.regions
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;

-- 3. branch_id on the records that already carry region_id ----------------
ALTER TABLE public.deals
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.organisations
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.research_campaigns
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id) ON DELETE SET NULL;

-- 4. Branch-level user scoping (mirrors system_user_regions) --------------
CREATE TABLE IF NOT EXISTS public.system_user_branches (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_user_id bigint NOT NULL REFERENCES public.system_users(id) ON DELETE CASCADE,
    branch_id      bigint NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
    created_at     timestamp with time zone DEFAULT now() NOT NULL,
    created_by     bigint REFERENCES public.people(id),
    CONSTRAINT system_user_branches_user_branch_key UNIQUE (system_user_id, branch_id)
);
CREATE INDEX IF NOT EXISTS idx_system_user_branches_user
  ON public.system_user_branches USING btree (system_user_id);
GRANT ALL ON TABLE public.system_user_branches TO anon;
GRANT ALL ON TABLE public.system_user_branches TO authenticated;
GRANT ALL ON TABLE public.system_user_branches TO service_role;

-- 5. Seed branches + map current regions ----------------------------------
INSERT INTO public.branches (name)
SELECT 'Cape Town' WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE name = 'Cape Town');
INSERT INTO public.branches (name)
SELECT 'Centurion' WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE name = 'Centurion');

-- Western Cape → Cape Town, Inland → Centurion
UPDATE public.regions SET branch_id = (SELECT id FROM public.branches WHERE name = 'Cape Town')
  WHERE name = 'Western Cape';
UPDATE public.regions SET branch_id = (SELECT id FROM public.branches WHERE name = 'Centurion')
  WHERE name = 'Inland';

-- 6. Backfill record branch_id from each record's region (only where unset
--    so a re-run never clobbers a manual override).
UPDATE public.deals              d SET branch_id = r.branch_id FROM public.regions r WHERE d.region_id = r.id AND d.branch_id IS NULL;
UPDATE public.leads              l SET branch_id = r.branch_id FROM public.regions r WHERE l.region_id = r.id AND l.branch_id IS NULL;
UPDATE public.organisations      o SET branch_id = r.branch_id FROM public.regions r WHERE o.region_id = r.id AND o.branch_id IS NULL;
UPDATE public.research_campaigns c SET branch_id = r.branch_id FROM public.regions r WHERE c.region_id = r.id AND c.branch_id IS NULL;
UPDATE public.sales_campaigns    s SET branch_id = r.branch_id FROM public.regions r WHERE s.region_id = r.id AND s.branch_id IS NULL;

-- ───────────────────────────────────────────── sql/add_menu_section_permissions.sql
-- Per-section "show this sidebar section" permissions for the 6 top-level menu
-- sections. Holding the permission displays the section; without it the section
-- is hidden. Items inside keep their own per-page permissions.
-- Rollout-safe: every new permission is granted to every existing role so the
-- current sidebar is unchanged until an admin revokes one.
-- Idempotent — safe to re-run.

INSERT INTO public.permissions (name, description)
SELECT v.name, v.description FROM (VALUES
  ('view_section_marketing',          'Show the Marketing menu section in the sidebar'),
  ('view_section_sales_management',   'Show the Sales Management menu section in the sidebar'),
  ('view_section_contract_management','Show the Contract Management menu section in the sidebar'),
  ('view_section_project_management', 'Show the Project Management menu section in the sidebar'),
  ('view_section_clients_contacts',   'Show the Clients & Contacts menu section in the sidebar'),
  ('view_section_site_admin',         'Show the Site Admin menu section in the sidebar')
) AS v(name, description)
WHERE NOT EXISTS (SELECT 1 FROM public.permissions p WHERE p.name = v.name);

-- Preserve current visibility: grant every new section permission to every role.
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE p.name IN (
    'view_section_marketing','view_section_sales_management','view_section_contract_management',
    'view_section_project_management','view_section_clients_contacts','view_section_site_admin')
  AND NOT EXISTS (
    SELECT 1 FROM public.role_permissions rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);

-- ───────────────────────────────────────────── sql/add_lead_source_options.sql
-- Lead Sources: configurable lookup + new options
-- =================================================
-- 1. Add an `is_system` flag so the four name-coupled sources (Referral,
--    Client Expansion, Research Campaign, Sales Campaign) can be protected in
--    the new Admin → Lookups → Lead Sources page: editable/deactivatable but
--    name-locked and undeletable, because conditional UI on the lead form keys
--    off their exact name. All other sources are fully user-managed.
-- 2. Add three new sources: Networking Events, Cold Calling, Network Leverage.
--
-- Idempotent: safe to re-run. Assumes rename_research_drop_campaign_sources.sql
-- has already run (so "Research" is now "Research Campaign"); the UPDATE below
-- covers both names just in case.

-- 1. Column ----------------------------------------------------------------
ALTER TABLE public.lead_sources
  ADD COLUMN IF NOT EXISTS is_system boolean NOT NULL DEFAULT false;

-- 2. Flag the system sources (name is load-bearing for lead-form logic) ------
UPDATE public.lead_sources
   SET is_system = true
 WHERE name IN ('Referral', 'Client Expansion', 'Research Campaign', 'Research', 'Sales Campaign');

-- 3. Seed the new sources ---------------------------------------------------
INSERT INTO public.lead_sources (name, active, is_system)
SELECT v.name, true, false
  FROM (VALUES
    ('Networking Events'),
    ('Cold Calling'),
    ('Network Leverage')
  ) AS v(name)
 WHERE NOT EXISTS (
   SELECT 1 FROM public.lead_sources ls WHERE ls.name = v.name
 );

-- ───────────────────────────────────────────── sql/add_lead_cadence_started.sql
-- Explicit cadence-start anchor on leads (cadence direction #3)
-- ============================================================
-- Replaces the fuzzy "day 0 = earliest interaction / created_at" inference with a
-- stored anchor date. Stamped at promote (when the lead enters the campaign);
-- the ribbon, the engagement-modal pre-fill, and the cockpit Work Queue all read
-- `cadence_started_at` (falling back to created_at for older / form-created leads),
-- so cadence due dates are deterministic and stable across interaction edits.
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS cadence_started_at date;

COMMIT;
-- ▲ End PART 1 (core)


-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  PART 2 — QUOTE TOOL  (each phase has its own BEGIN/COMMIT)            ║
-- ╚═══════════════════════════════════════════════════════════════════════╝

-- ═════════════════════════════════════════════ sql/quote_tool_phase_a.sql
-- ═══════════════════════════════════════════════════════════════════════
-- Quote Tool — Phase A schema (PROPOSAL, NOT EXECUTED)
-- ═══════════════════════════════════════════════════════════════════════
-- Target: Dev (test branch) only. Do NOT run on Production until reviewed.
--
-- Scope:
--   • 4 lookup tables (grades, areas, leave types, shared salary option types)
--   • 8 effective-dated rate / catalog tables (HR Setup tiles)
--   • Indexes for the "latest rate as of X" lookup pattern
--   • Current-rate views (one per rate-card table)
--   • 1 new permission row (administer_quote_rates)
--
-- Conventions (matches Focus CLAUDE.md):
--   • IDs: BIGINT / BIGSERIAL
--   • Timestamps: TIMESTAMPTZ for audit, DATE for calendar-day effective dates
--   • Ownership: owner_id, created_by → people(id)
--   • Table prefix: quote_ (namespacing under public; avoids collisions)
--   • Naming: snake_case, typos fixed vs. Xone (e.g. "multiplier" not "muliplier",
--     "occurrence_type" not "occurance_type")
--
-- RLS:
--   • This file does NOT enable RLS — matches Focus's existing pattern.
--   • If you choose Option B (RLS on rate cards), an additional file
--     quote_tool_phase_a_rls.sql will add policies + a helper function.
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. LOOKUPS ────────────────────────────────────────────────────────

CREATE TABLE quote_grades (
  id            BIGSERIAL    PRIMARY KEY,
  code          TEXT         NOT NULL UNIQUE,        -- 'A','B','C','D','E'
  description   TEXT         NOT NULL,               -- 'Grade A'
  display_order SMALLINT,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE quote_areas (
  id            BIGSERIAL    PRIMARY KEY,
  code          TEXT         NOT NULL UNIQUE,        -- 'area_1','area_2','area_3'
  description   TEXT         NOT NULL,               -- 'Area 1 (Major Urban)'
  display_order SMALLINT,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE quote_leave_types (
  id            BIGSERIAL    PRIMARY KEY,
  code          TEXT         NOT NULL UNIQUE,        -- 'sick','annual','family_responsibility','maternity','study'
  description   TEXT         NOT NULL,               -- 'Sick Leave'
  display_order SMALLINT,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE quote_shared_salary_option_types (
  id            BIGSERIAL    PRIMARY KEY,
  code          TEXT         NOT NULL UNIQUE,        -- 'health_insurance','provident_fund','bargaining_council','compensation_commissioner','uif','sdl'
  description   TEXT         NOT NULL,               -- 'Health Insurance'
  display_order SMALLINT,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 2. RATE-CARD TABLES ──────────────────────────────────────────────
--
-- Each rate-card row has an effective_date. To find the rate for a given
-- as-of date, query: WHERE effective_date <= $as_of ORDER BY effective_date DESC LIMIT 1
-- per natural key. The current-rate views below do this for "today".

-- ── 2.1 Statutory Salary Rates ───────────────────────────────────────

CREATE TABLE quote_salary_rates (
  id              BIGSERIAL    PRIMARY KEY,
  effective_date  DATE         NOT NULL,
  grade_id        BIGINT       NOT NULL REFERENCES quote_grades(id),
  area_id         BIGINT       NOT NULL REFERENCES quote_areas(id),
  monthly_salary  NUMERIC(12,2) NOT NULL,
  hourly_rate     NUMERIC(8,4)  NOT NULL,
  owner_id        BIGINT       REFERENCES people(id),
  created_by      BIGINT       REFERENCES people(id),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  UNIQUE (effective_date, grade_id, area_id)
);
CREATE INDEX idx_salary_rates_lookup
  ON quote_salary_rates (grade_id, area_id, effective_date DESC);

-- ── 2.2 Extraordinary Hours Rates ────────────────────────────────────
-- Only one row per effective_date. Multipliers are "premium-only" on top
-- of monthly salary (see xone-multiplier-convention memory note).

CREATE TABLE quote_extraordinary_hour_rates (
  id                          BIGSERIAL    PRIMARY KEY,
  effective_date              DATE         NOT NULL UNIQUE,
  overtime_multiplier         NUMERIC(5,3) NOT NULL,
  sunday_multiplier           NUMERIC(5,3) NOT NULL,
  public_holiday_multiplier   NUMERIC(5,3) NOT NULL,
  owner_id                    BIGINT       REFERENCES people(id),
  created_by                  BIGINT       REFERENCES people(id),
  created_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 2.3 Statutory Allowances ─────────────────────────────────────────
-- Each statutory allowance (Night Shift, Cleaning, Control Centre Op etc.)
-- has a code/slug for stable calc-engine reference, plus a human description
-- for the UI. occurrence_type tells the engine whether the rate is per shift
-- or per month.

CREATE TABLE quote_statutory_allowances (
  id              BIGSERIAL    PRIMARY KEY,
  effective_date  DATE         NOT NULL,
  code            TEXT         NOT NULL,            -- 'cleaning','night_shift','control_centre_operator'…
  description     TEXT         NOT NULL,            -- 'Cleaning Allowance','Night Shift'…
  rate            NUMERIC(10,2) NOT NULL,
  occurrence_type TEXT         NOT NULL CHECK (occurrence_type IN ('shift','monthly')),
  owner_id        BIGINT       REFERENCES people(id),
  created_by      BIGINT       REFERENCES people(id),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  UNIQUE (effective_date, code)
);
CREATE INDEX idx_statutory_allowances_lookup
  ON quote_statutory_allowances (code, effective_date DESC);

-- ── 2.4 Leave Allocations ────────────────────────────────────────────

CREATE TABLE quote_leave_allocations (
  id                  BIGSERIAL    PRIMARY KEY,
  effective_from_date DATE         NOT NULL,
  leave_type_id       BIGINT       NOT NULL REFERENCES quote_leave_types(id),
  no_of_days          INTEGER      NOT NULL CHECK (no_of_days >= 0),
  cycle_days          INTEGER      NOT NULL CHECK (cycle_days > 0),
  average_utilisation NUMERIC(5,2) NOT NULL CHECK (average_utilisation BETWEEN 0 AND 100),  -- percentage
  owner_id            BIGINT       REFERENCES people(id),
  created_by          BIGINT       REFERENCES people(id),
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  UNIQUE (effective_from_date, leave_type_id)
);
CREATE INDEX idx_leave_allocations_lookup
  ON quote_leave_allocations (leave_type_id, effective_from_date DESC);

-- ── 2.5 Shared Salary Options ────────────────────────────────────────
-- Covers Health Insurance, Provident Fund, Bargaining Council Levy,
-- Compensation Commissioner, UIF Recovery, SDL Recovery.
-- The UI surfaces these as 6 separate tiles, filtered by type.

CREATE TABLE quote_shared_salary_options (
  id                            BIGSERIAL    PRIMARY KEY,
  effective_date                DATE         NOT NULL,
  shared_salary_option_type_id  BIGINT       NOT NULL REFERENCES quote_shared_salary_option_types(id),
  employee_contribution         NUMERIC(10,4) NOT NULL,    -- % or absolute, depending on type
  employer_contribution         NUMERIC(10,4) NOT NULL,
  threshold                     NUMERIC(12,2) NOT NULL DEFAULT 0,
  owner_id                      BIGINT       REFERENCES people(id),
  created_by                    BIGINT       REFERENCES people(id),
  created_at                    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  UNIQUE (effective_date, shared_salary_option_type_id)
);
CREATE INDEX idx_shared_salary_options_lookup
  ON quote_shared_salary_options (shared_salary_option_type_id, effective_date DESC);

-- ── 2.6 Calculation Ratios ───────────────────────────────────────────
-- Covers Replacement Pool Provision, Area Management Overhead, HR Calculation Ratios.
-- code is the stable calc-engine reference; description is the human label.
-- ratio_value is TEXT to support various units (percentage, hours, days, multiplier).

CREATE TABLE quote_calculation_ratios (
  id                BIGSERIAL    PRIMARY KEY,
  effective_date    DATE         NOT NULL,
  code              TEXT         NOT NULL,    -- 'replacement_pool_provision','area_manager_overhead','avg_shifts_per_month','sunday_hours_per_month'…
  description       TEXT         NOT NULL,    -- 'Replacement Pool Provision','Area Manager Overhead'…
  ratio_value       TEXT         NOT NULL,    -- the actual number (stored as text to preserve precision of computed ratios)
  unit              TEXT,                     -- 'hours','shifts','%','Rand','Days','Numeric Multiplier'
  enabled           BOOLEAN      NOT NULL DEFAULT true,
  calculation_note  TEXT,
  owner_id          BIGINT       REFERENCES people(id),
  created_by        BIGINT       REFERENCES people(id),
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  UNIQUE (effective_date, code)
);
CREATE INDEX idx_calculation_ratios_lookup
  ON quote_calculation_ratios (code, effective_date DESC);

-- ── 2.7 Discretionary Allowances (catalog) ───────────────────────────
-- These are catalog entries used to drive the per-post allowance UI.
-- Effective-dated for consistency (Xone has no date on these; you said
-- to add it).

CREATE TABLE quote_discretionary_allowances (
  id              BIGSERIAL    PRIMARY KEY,
  effective_date  DATE         NOT NULL,
  code            TEXT         NOT NULL,    -- 'seniority','supervisor','drivers','transport'…
  name            TEXT         NOT NULL,    -- 'Seniority Allowance'
  description     TEXT,
  display_order   SMALLINT,
  owner_id        BIGINT       REFERENCES people(id),
  created_by      BIGINT       REFERENCES people(id),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  UNIQUE (effective_date, code)
);

-- ── 2.8 Discretionary Incentives (catalog) ───────────────────────────

CREATE TABLE quote_discretionary_incentives (
  id              BIGSERIAL    PRIMARY KEY,
  effective_date  DATE         NOT NULL,
  code            TEXT         NOT NULL,    -- 'performance','attendance'
  name            TEXT         NOT NULL,    -- 'Performance Incentive'
  description     TEXT,
  display_order   SMALLINT,
  owner_id        BIGINT       REFERENCES people(id),
  created_by      BIGINT       REFERENCES people(id),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  UNIQUE (effective_date, code)
);

-- ── 3. CURRENT-RATE VIEWS ────────────────────────────────────────────
-- One view per rate-card table. Returns the latest row per natural key
-- whose effective_date <= today. The calc engine uses these to answer
-- "what's the rate right now?" without joining/filtering itself.

CREATE OR REPLACE VIEW v_quote_salary_rates_current AS
SELECT DISTINCT ON (grade_id, area_id) *
FROM quote_salary_rates
WHERE effective_date <= CURRENT_DATE
ORDER BY grade_id, area_id, effective_date DESC;

CREATE OR REPLACE VIEW v_quote_extraordinary_hour_rates_current AS
SELECT *
FROM quote_extraordinary_hour_rates
WHERE effective_date <= CURRENT_DATE
ORDER BY effective_date DESC
LIMIT 1;

CREATE OR REPLACE VIEW v_quote_statutory_allowances_current AS
SELECT DISTINCT ON (code) *
FROM quote_statutory_allowances
WHERE effective_date <= CURRENT_DATE
ORDER BY code, effective_date DESC;

CREATE OR REPLACE VIEW v_quote_leave_allocations_current AS
SELECT DISTINCT ON (leave_type_id) *
FROM quote_leave_allocations
WHERE effective_from_date <= CURRENT_DATE
ORDER BY leave_type_id, effective_from_date DESC;

CREATE OR REPLACE VIEW v_quote_shared_salary_options_current AS
SELECT DISTINCT ON (shared_salary_option_type_id) *
FROM quote_shared_salary_options
WHERE effective_date <= CURRENT_DATE
ORDER BY shared_salary_option_type_id, effective_date DESC;

CREATE OR REPLACE VIEW v_quote_calculation_ratios_current AS
SELECT DISTINCT ON (code) *
FROM quote_calculation_ratios
WHERE effective_date <= CURRENT_DATE AND enabled = true
ORDER BY code, effective_date DESC;

CREATE OR REPLACE VIEW v_quote_discretionary_allowances_current AS
SELECT DISTINCT ON (code) *
FROM quote_discretionary_allowances
WHERE effective_date <= CURRENT_DATE
ORDER BY code, effective_date DESC;

CREATE OR REPLACE VIEW v_quote_discretionary_incentives_current AS
SELECT DISTINCT ON (code) *
FROM quote_discretionary_incentives
WHERE effective_date <= CURRENT_DATE
ORDER BY code, effective_date DESC;

-- ── 4. PERMISSION ────────────────────────────────────────────────────

INSERT INTO permissions (name, description)
VALUES ('administer_quote_rates', 'Edit Quote Tool rate cards (HR Setup, etc.)')
ON CONFLICT (name) DO NOTHING;

-- After this runs, manually wire this permission to the Administrator role
-- via Focus's existing Role Permissions UI.

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════
-- SEED DATA (separate file)
-- ═══════════════════════════════════════════════════════════════════════
-- Seed inserts for lookups + rate cards (from the prototype data) will
-- live in sql/quote_tool_phase_a_seed.sql. Run that file ONLY after this
-- one has been applied and reviewed.

-- ═════════════════════════════════════════════ sql/quote_tool_phase_a_seed.sql
-- ═══════════════════════════════════════════════════════════════════════
-- Quote Tool — Phase A seed data (PROPOSAL, NOT EXECUTED)
-- ═══════════════════════════════════════════════════════════════════════
-- Target: Dev (test branch) only. Run AFTER quote_tool_phase_a.sql.
--
-- Source: the verified seed data from the quote-posts prototype
-- (quote-posts-prototype.html, defaultHrAdminData()), which mirrors what
-- Richard confirmed against the Xone admin screens.
--
-- All inserts reference lookup IDs by code via sub-SELECT, so they work
-- regardless of which BIGSERIAL values get assigned.
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. LOOKUPS ────────────────────────────────────────────────────────

INSERT INTO quote_grades (code, description, display_order) VALUES
  ('A', 'Grade A', 1),
  ('B', 'Grade B', 2),
  ('C', 'Grade C', 3),
  ('D', 'Grade D', 4),
  ('E', 'Grade E', 5)
ON CONFLICT (code) DO NOTHING;

INSERT INTO quote_areas (code, description, display_order) VALUES
  ('area_1', 'Area 1 (Major Urban)', 1),
  ('area_2', 'Area 2 (Urban)',       2),
  ('area_3', 'Area 3 (Other)',       3)
ON CONFLICT (code) DO NOTHING;

INSERT INTO quote_leave_types (code, description, display_order) VALUES
  ('sick',                  'Sick Leave',             1),
  ('annual',                'Annual Leave',           2),
  ('family_responsibility', 'Family Responsibility',  3),
  ('maternity',             'Maternity Leave',        4),
  ('study',                 'Study Leave',            5)
ON CONFLICT (code) DO NOTHING;

INSERT INTO quote_shared_salary_option_types (code, description, display_order) VALUES
  ('health_insurance',          'Health Insurance',          1),
  ('provident_fund',            'Provident Fund',            2),
  ('bargaining_council_levy',   'Bargaining Council Levy',   3),
  ('compensation_commissioner', 'Compensation Commissioner', 4),
  ('uif',                       'UIF',                       5),
  ('sdl',                       'SDL',                       6)
ON CONFLICT (code) DO NOTHING;

-- ── 2. STATUTORY SALARY RATES ────────────────────────────────────────
-- 16 rows across 2023/2024/2025 effective dates (from the visible Xone data).

INSERT INTO quote_salary_rates (effective_date, grade_id, area_id, monthly_salary, hourly_rate) VALUES
  -- 2023/03/01
  ('2023-03-01', (SELECT id FROM quote_grades WHERE code='A'), (SELECT id FROM quote_areas WHERE code='area_1'), 6907.00, 33.2100),
  ('2023-03-01', (SELECT id FROM quote_grades WHERE code='B'), (SELECT id FROM quote_areas WHERE code='area_1'), 6330.00, 30.4300),
  ('2023-03-01', (SELECT id FROM quote_grades WHERE code='C'), (SELECT id FROM quote_areas WHERE code='area_1'), 5726.00, 27.5300),
  ('2023-03-01', (SELECT id FROM quote_grades WHERE code='A'), (SELECT id FROM quote_areas WHERE code='area_3'), 5915.00, 28.4400),
  ('2023-03-01', (SELECT id FROM quote_grades WHERE code='B'), (SELECT id FROM quote_areas WHERE code='area_3'), 5499.00, 26.4400),
  ('2023-03-01', (SELECT id FROM quote_grades WHERE code='C'), (SELECT id FROM quote_areas WHERE code='area_3'), 5499.00, 26.4400),
  -- 2024/03/01
  ('2024-03-01', (SELECT id FROM quote_grades WHERE code='A'), (SELECT id FROM quote_areas WHERE code='area_1'), 7277.00, 34.9900),
  ('2024-03-01', (SELECT id FROM quote_grades WHERE code='B'), (SELECT id FROM quote_areas WHERE code='area_1'), 6700.00, 32.2100),
  ('2024-03-01', (SELECT id FROM quote_grades WHERE code='C'), (SELECT id FROM quote_areas WHERE code='area_1'), 6096.00, 29.3100),
  ('2024-03-01', (SELECT id FROM quote_grades WHERE code='A'), (SELECT id FROM quote_areas WHERE code='area_3'), 6271.00, 30.1500),
  ('2024-03-01', (SELECT id FROM quote_grades WHERE code='B'), (SELECT id FROM quote_areas WHERE code='area_3'), 5855.00, 28.1500),
  ('2024-03-01', (SELECT id FROM quote_grades WHERE code='C'), (SELECT id FROM quote_areas WHERE code='area_3'), 5855.00, 28.1500),
  -- 2025/03/01
  ('2025-03-01', (SELECT id FROM quote_grades WHERE code='A'), (SELECT id FROM quote_areas WHERE code='area_1'), 7695.00, 37.0000),
  ('2025-03-01', (SELECT id FROM quote_grades WHERE code='B'), (SELECT id FROM quote_areas WHERE code='area_1'), 7118.00, 34.2200),
  ('2025-03-01', (SELECT id FROM quote_grades WHERE code='C'), (SELECT id FROM quote_areas WHERE code='area_1'), 6514.00, 31.3200),
  ('2025-03-01', (SELECT id FROM quote_grades WHERE code='A'), (SELECT id FROM quote_areas WHERE code='area_3'), 6672.00, 32.0800);

-- ── 3. EXTRAORDINARY HOURS RATES ─────────────────────────────────────
-- 1 row. Multipliers are premium-only (see xone-multiplier-convention memory).

INSERT INTO quote_extraordinary_hour_rates (effective_date, overtime_multiplier, sunday_multiplier, public_holiday_multiplier) VALUES
  ('2023-03-01', 1.500, 1.500, 1.000);

-- ── 4. STATUTORY ALLOWANCES ──────────────────────────────────────────
-- 32 rows across 2023/2024/2025/2026 effective dates.
-- code = stable slug for the calc engine; description = display label.

INSERT INTO quote_statutory_allowances (effective_date, code, description, rate, occurrence_type) VALUES
  -- 2023/03/01
  ('2023-03-01', 'control_centre_operator',   'Control Centre Operator',    8.50, 'shift'),
  ('2023-03-01', 'mobile_supervisor',         'Mobile Supervisor',          8.50, 'shift'),
  ('2023-03-01', 'armed_response_officer',    'Armed Response Officer',     8.50, 'shift'),
  ('2023-03-01', 'armed_security_operator',   'Armed Security Operator',    8.50, 'shift'),
  ('2023-03-01', 'national_key_point_officer','National Key Point Officer', 8.50, 'shift'),
  ('2023-03-01', 'cleaning',                  'Cleaning Allowance',         30.00,'monthly'),
  ('2023-03-01', 'night_shift',               'Night Shift',                6.00, 'shift'),
  ('2023-03-01', 'canine_dog_handler',        'Canine/Dog Handler',         8.50, 'shift'),
  -- 2024/03/01 (rate increases)
  ('2024-03-01', 'night_shift',               'Night Shift',                7.00, 'shift'),
  ('2024-03-01', 'armed_security_operator',   'Armed Security Operator',    9.50, 'shift'),
  ('2024-03-01', 'cleaning',                  'Cleaning Allowance',         31.00,'monthly'),
  ('2024-03-01', 'control_centre_operator',   'Control Centre Operator',    9.50, 'shift'),
  ('2024-03-01', 'canine_dog_handler',        'Canine/Dog Handler',         9.50, 'shift'),
  ('2024-03-01', 'mobile_supervisor',         'Mobile Supervisor',          9.50, 'shift'),
  ('2024-03-01', 'armed_response_officer',    'Armed Response Officer',     9.50, 'shift'),
  ('2024-03-01', 'national_key_point_officer','National Key Point Officer', 9.50, 'shift'),
  -- 2025/03/01 (held flat)
  ('2025-03-01', 'national_key_point_officer','National Key Point Officer', 9.50, 'shift'),
  ('2025-03-01', 'canine_dog_handler',        'Canine/Dog Handler',         9.50, 'shift'),
  ('2025-03-01', 'armed_response_officer',    'Armed Response Officer',     9.50, 'shift'),
  ('2025-03-01', 'mobile_supervisor',         'Mobile Supervisor',          9.50, 'shift'),
  ('2025-03-01', 'control_centre_operator',   'Control Centre Operator',    9.50, 'shift'),
  ('2025-03-01', 'cleaning',                  'Cleaning Allowance',         31.00,'monthly'),
  ('2025-03-01', 'armed_security_operator',   'Armed Security Operator',    9.50, 'shift'),
  ('2025-03-01', 'night_shift',               'Night Shift',                7.00, 'shift'),
  -- 2026/03/01 (next increase)
  ('2026-03-01', 'night_shift',               'Night Shift',                8.00, 'shift'),
  ('2026-03-01', 'armed_security_operator',   'Armed Security Operator',    10.50,'shift'),
  ('2026-03-01', 'cleaning',                  'Cleaning Allowance',         32.00,'monthly'),
  ('2026-03-01', 'control_centre_operator',   'Control Centre Operator',    10.50,'shift'),
  ('2026-03-01', 'mobile_supervisor',         'Mobile Supervisor',          10.50,'shift'),
  ('2026-03-01', 'armed_response_officer',    'Armed Response Officer',     10.50,'shift'),
  ('2026-03-01', 'canine_dog_handler',        'Canine/Dog Handler',         10.50,'shift'),
  ('2026-03-01', 'national_key_point_officer','National Key Point Officer', 10.50,'shift');

-- ── 5. LEAVE ALLOCATIONS ─────────────────────────────────────────────
-- 5 leave types, each one row at the baseline date.

INSERT INTO quote_leave_allocations (effective_from_date, leave_type_id, no_of_days, cycle_days, average_utilisation) VALUES
  ('2023-03-01', (SELECT id FROM quote_leave_types WHERE code='sick'),                  30,  1095, 60.00),
  ('2023-03-01', (SELECT id FROM quote_leave_types WHERE code='annual'),                22,  365,  100.00),
  ('2023-03-01', (SELECT id FROM quote_leave_types WHERE code='family_responsibility'),  5,  365,  66.00),
  ('2023-03-01', (SELECT id FROM quote_leave_types WHERE code='maternity'),             120, 365,  1.00),
  ('2023-03-01', (SELECT id FROM quote_leave_types WHERE code='study'),                  6,  365,  5.00);

-- ── 6. SHARED SALARY OPTIONS ─────────────────────────────────────────
-- One row per type. employee/employer values per type vary in meaning:
-- Provident Fund + UIF + SDL → percentages; Health Insurance + Bargaining
-- Council + Compensation Commissioner → absolute amounts. UI/calc engine
-- knows which is which by type code.

INSERT INTO quote_shared_salary_options (effective_date, shared_salary_option_type_id, employee_contribution, employer_contribution, threshold) VALUES
  ('2023-03-01', (SELECT id FROM quote_shared_salary_option_types WHERE code='health_insurance'),           0.0000, 172.5000, 0.00),
  ('2023-03-01', (SELECT id FROM quote_shared_salary_option_types WHERE code='provident_fund'),             7.5000, 7.5000,   0.00),
  ('2023-03-01', (SELECT id FROM quote_shared_salary_option_types WHERE code='bargaining_council_levy'),    0.0000, 7.0000,   0.00),
  ('2023-03-01', (SELECT id FROM quote_shared_salary_option_types WHERE code='compensation_commissioner'),  0.0000, 2.6500,   0.00),
  ('2023-03-01', (SELECT id FROM quote_shared_salary_option_types WHERE code='uif'),                        1.0000, 1.0000,   0.00),
  ('2023-03-01', (SELECT id FROM quote_shared_salary_option_types WHERE code='sdl'),                        0.0000, 1.0000,   0.00);

-- ── 7. CALCULATION RATIOS ────────────────────────────────────────────
-- 12 named ratios. Code = stable slug; description = human label;
-- ratio_value = TEXT to preserve precision of computed ratios.

INSERT INTO quote_calculation_ratios (effective_date, code, description, ratio_value, unit, enabled) VALUES
  ('2024-01-02', 'avg_sunday_hours_per_month',          'Average Sunday hours per person per month',         '34.78571429', 'Hours',  true),
  ('2024-01-02', 'avg_ph_hours_per_month',              'Average Public Holiday hours per person per month', '8.83333333',  'Hours',  true),
  ('2024-01-02', 'max_overtime_hours_per_month',        'Maximum Overtime hours per person per month',       '52.17857',    'Hours',  true),
  ('2024-01-02', 'avg_night_shifts_per_month',          'Average Night Shifts person per month',             '10.14583',    'Shifts', true),
  ('2024-01-02', 'monthly_bonus_provision_pct',         'Monthly Bonus Provision %',                         '8.33333333',  '%',      true),
  ('2024-01-02', 'monthly_5yr_service_bonus_provision', 'Monthly 5-year Service Bonus Provision',            '8.3333333',   'Rand',   true),
  ('2024-01-17', 'psira_contribution',                  'Psira Contribution',                                '4.6',         'Rand',   true),
  ('2024-01-17', 'area_manager_overhead',               'Area Manager Overhead',                             '0',           '%',      true),
  ('2024-01-17', 'replacement_pool_provision',          'Replacement Pool Provision',                        '0',           '%',      true),
  ('2023-12-01', 'avg_shifts_per_month',                'Average Shifts per person per Month',               '20.29166667', 'Shifts', true),
  ('2024-05-26', 'min_fixed_salary_to_psira_ratio',     'Minimum Fixed Salary to PSIRA Ratio',               '1',           'Numeric Multiplier', true),
  ('2024-06-01', 'avg_unauthorised_absent_days',        'Average number of unauthorised absent days per month', '2',        'Days',   true);

-- ── 8. DISCRETIONARY ALLOWANCES (catalog) ────────────────────────────
-- Rich descriptions from the Xone admin screen.

INSERT INTO quote_discretionary_allowances (effective_date, code, name, description, display_order) VALUES
  ('2023-03-01', 'seniority',       'Seniority Allowance',       'Rank and/or duration in the role.', 1),
  ('2023-03-01', 'supervisor',      'Supervisor Allowance',      'Works in a supervisory capacity, oversees team. Small sites with no Contract Manager. Senior staff allocated this allowance to pick up additional managerial work.', 2),
  ('2023-03-01', 'drivers',         'Drivers Allowance',         'Driving vehicles as per role requirement. eg. Armed Response Officers and RSI''s', 3),
  ('2023-03-01', 'transport',       'Transport Allowance',       'Allocated to sites where client pays for transport for staff', 4),
  ('2023-03-01', 'top_up',          'Top Up Allowance',          'Add this to increase total earnings. Eg PAR Staff', 5),
  ('2023-03-01', 'special_post',    'Special Post Allowance',    'Danger, inconvenience, complexity of role and responsibilities', 6),
  ('2023-03-01', 'customer_funded', 'Customer Funded Allowance', 'Paid specifically by clients - e.g. UWC.', 7),
  ('2023-03-01', 'stand_in',        'Stand-In Allowance',        'Ad-hoc allowance paid for leave stand-in', 8),
  ('2023-03-01', 'standby',         'Standby Allowance',         'Paid to Technician - only if they are rostered to be on standby.', 9);

-- ── 9. DISCRETIONARY INCENTIVES (catalog) ────────────────────────────

INSERT INTO quote_discretionary_incentives (effective_date, code, name, description, display_order) VALUES
  ('2023-03-01', 'performance', 'Performance Incentive', 'Performance Incentive', 1),
  ('2023-03-01', 'attendance',  'Attendance Incentive',  'Attendance Incentive',  2);

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════
-- Verification queries (run these after seeding to sanity-check)
-- ═══════════════════════════════════════════════════════════════════════
--
-- SELECT 'salary rates'          AS what, count(*) FROM quote_salary_rates
-- UNION ALL SELECT 'eh rates',             count(*) FROM quote_extraordinary_hour_rates
-- UNION ALL SELECT 'statutory allowances', count(*) FROM quote_statutory_allowances
-- UNION ALL SELECT 'leave allocations',    count(*) FROM quote_leave_allocations
-- UNION ALL SELECT 'shared salary options',count(*) FROM quote_shared_salary_options
-- UNION ALL SELECT 'calc ratios',          count(*) FROM quote_calculation_ratios
-- UNION ALL SELECT 'disc allowances',      count(*) FROM quote_discretionary_allowances
-- UNION ALL SELECT 'disc incentives',      count(*) FROM quote_discretionary_incentives;
--
-- Expected totals:
--   salary rates: 16
--   eh rates:     1
--   statutory:    32
--   leave:        5
--   shared:       6
--   calc ratios:  12
--   disc allow:   9
--   disc incent:  2
-- ═══════════════════════════════════════════════════════════════════════

-- ═════════════════════════════════════════════ sql/quote_tool_phase_b.sql
-- ═══════════════════════════════════════════════════════════════════════
-- Quote Tool — Phase B schema (PROPOSAL, NOT EXECUTED)
-- ═══════════════════════════════════════════════════════════════════════
-- Target: Dev (test branch) only. Run AFTER Phase A (quote_tool_phase_a.sql
-- and quote_tool_phase_a_seed.sql) is applied and verified.
--
-- Scope (Phase B-1):
--   • quote_sites      — Organisation → Site → Quote linkage
--   • quote_quotes     — quote header; mandatory FK to deals(id)
--   • quote_posts      — posts within a quote, FK to quote
--   • quote_post_shifts — shift schedule cells per post
--   • quote_snapshots  — frozen rate-card values used at calc time (audit)
--   • Permissions: create_quote, view_all_quotes
--
-- Deferred to Phase B-2 (when the UI surfaces them):
--   • quote_post_allowances    (m2m to quote_discretionary_allowances)
--   • quote_post_incentives    (m2m to quote_discretionary_incentives)
--   • quote_post_statutory     (m2m to quote_statutory_allowances)
--   • quote_post_accessories, quote_post_training (catalogs not yet built)
--
-- Proposal Builder integration:
--   • The Proposal Builder UI is a new tab on Focus's Opportunity page
--   • A deal can have N quotes; each quote points to its deal
--   • Site context optionally sits on the quote (not the deal) for now —
--     a deal could have quotes for different sites later
--
-- Conventions (same as Phase A):
--   • IDs: BIGINT / BIGSERIAL
--   • Audit: owner_id, created_by → people(id); created_at/updated_at TIMESTAMPTZ
--   • Table prefix: quote_
--   • Naming: snake_case
--   • No RLS (matches Focus pattern; tighten later — see focus-no-rls-app-layer-security memory)
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. SITES ──────────────────────────────────────────────────────────
-- A physical location belonging to an organisation. One org can have many
-- sites; one site can host many quotes over time.

CREATE TABLE quote_sites (
  id              BIGSERIAL    PRIMARY KEY,
  organisation_id BIGINT       NOT NULL REFERENCES organisations(id) ON DELETE RESTRICT,
  name            TEXT         NOT NULL,                                -- 'RCL Sugar Komati Plant'
  address_line1   TEXT,
  address_city    TEXT,
  region          TEXT,                                                  -- 'Western Cape', 'Gauteng', 'Mpumalanga' (matches existing Focus region usage)
  area_id         BIGINT       REFERENCES quote_areas(id),              -- which salary area applies (for rate lookups)
  notes           TEXT,
  owner_id        BIGINT       REFERENCES people(id),
  created_by      BIGINT       REFERENCES people(id),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_quote_sites_org ON quote_sites (organisation_id);

-- ── 2. QUOTES ─────────────────────────────────────────────────────────
-- The quote header. Every quote is anchored to a deal (the Proposal Builder
-- tab is inside the deal). Sites are optional but the calc engine uses the
-- site's area_id for salary lookups if present, falling back to a default.
--
-- A "regeneration at a different date" creates a new row with original_quote_id
-- pointing at the source — both rows survive (coexist + linked).

CREATE TABLE quote_quotes (
  id                       BIGSERIAL    PRIMARY KEY,
  deal_id                  BIGINT       NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
  site_id                  BIGINT       REFERENCES quote_sites(id),
  original_quote_id        BIGINT       REFERENCES quote_quotes(id),  -- self-ref for revisions/regenerations
  version                  SMALLINT     NOT NULL DEFAULT 1,
  contract_name            TEXT         NOT NULL,
  quote_date               DATE         NOT NULL DEFAULT CURRENT_DATE,
  contract_start_date      DATE         NOT NULL,
  contract_duration_months SMALLINT     NOT NULL CHECK (contract_duration_months > 0),
  shifts_per_day           SMALLINT     NOT NULL DEFAULT 2 CHECK (shifts_per_day BETWEEN 1 AND 4),
  margin_pct               NUMERIC(5,2) NOT NULL DEFAULT 20.00,           -- true gross margin (price-side formula — see xone-margin-convention)
  status                   TEXT         NOT NULL DEFAULT 'draft'
                                       CHECK (status IN ('draft','sent','accepted','rejected','lost','expired')),
  valid_until              DATE,                                          -- typically quote_date + 30
  notes                    TEXT,
  owner_id                 BIGINT       REFERENCES people(id),
  created_by               BIGINT       REFERENCES people(id),
  created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_quote_quotes_deal     ON quote_quotes (deal_id);
CREATE INDEX idx_quote_quotes_status   ON quote_quotes (status);
CREATE INDEX idx_quote_quotes_original ON quote_quotes (original_quote_id) WHERE original_quote_id IS NOT NULL;

-- ── 3. POSTS ──────────────────────────────────────────────────────────
-- A post inside a quote. heading_text is freeform (e.g. 'Main Gate',
-- 'Response Team'); could be promoted to a FK lookup later. fixed_salary
-- overrides the grade-based salary if set (with the MinimumFixedSalaryPSIRA
-- ratio enforced in the calc engine).
--
-- ON DELETE CASCADE on quote_id: deleting a quote removes its posts.

CREATE TABLE quote_posts (
  id                        BIGSERIAL    PRIMARY KEY,
  quote_id                  BIGINT       NOT NULL REFERENCES quote_quotes(id) ON DELETE CASCADE,
  heading_text              TEXT,                                         -- 'Main Gate', 'Response Team', NULL = ungrouped
  display_order             SMALLINT     NOT NULL DEFAULT 0,
  name                      TEXT         NOT NULL,                        -- 'Security Officer', 'Senior Supervisor'
  grade_id                  BIGINT       REFERENCES quote_grades(id),
  area_id                   BIGINT       REFERENCES quote_areas(id),     -- can override the site's area
  uniform                   TEXT,                                         -- 'Combat', 'Formal', etc.
  description               TEXT,
  fixed_salary              NUMERIC(12,2),                                -- NULL = use grade-based salary lookup
  exclude_replacement_pool  BOOLEAN      NOT NULL DEFAULT false,
  margin_pct_override       NUMERIC(5,2),                                 -- NULL = use quote-level margin
  owner_id                  BIGINT       REFERENCES people(id),
  created_by                BIGINT       REFERENCES people(id),
  created_at                TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_quote_posts_quote ON quote_posts (quote_id);

-- ── 4. POST SHIFTS ────────────────────────────────────────────────────
-- One row per (post × shift_index × day_type). For a 2-shift post:
-- 2 shifts × 8 day-types = 16 rows. Max 4 × 8 = 32 rows per post.
-- num_officers = concurrent officers on duty for that shift on that day.

CREATE TABLE quote_post_shifts (
  post_id      BIGINT      NOT NULL REFERENCES quote_posts(id) ON DELETE CASCADE,
  shift_index  SMALLINT    NOT NULL CHECK (shift_index BETWEEN 1 AND 4),
  day_type     TEXT        NOT NULL CHECK (day_type IN
                            ('monday','tuesday','wednesday','thursday','friday',
                             'saturday','sunday','public_holiday')),
  num_officers SMALLINT    NOT NULL DEFAULT 0 CHECK (num_officers >= 0),
  start_time   TIME        NOT NULL,
  end_time     TIME        NOT NULL,
  PRIMARY KEY (post_id, shift_index, day_type)
);

-- ── 5. QUOTE SNAPSHOTS ────────────────────────────────────────────────
-- Frozen copy of the rate cards used at calc time. Allows "regenerate this
-- quote at the original date" + audit ("show me what rates we quoted off").
-- One row per calc event; the latest one is the canonical state.

CREATE TABLE quote_snapshots (
  id           BIGSERIAL    PRIMARY KEY,
  quote_id     BIGINT       NOT NULL REFERENCES quote_quotes(id) ON DELETE CASCADE,
  snapshot_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  as_of_date   DATE         NOT NULL,                                  -- the date the rates were looked up for
  rate_data    JSONB        NOT NULL,                                  -- full rate-card values applied: salary_rates, statutory_allowances, calculation_ratios, etc.
  created_by   BIGINT       REFERENCES people(id)
);
CREATE INDEX idx_quote_snapshots_quote ON quote_snapshots (quote_id, snapshot_at DESC);

-- ── 6. VIEWS ──────────────────────────────────────────────────────────
-- Display helpers — the Proposal Builder tab can SELECT from these.

CREATE OR REPLACE VIEW v_quote_quotes_full AS
SELECT
  q.id, q.deal_id, q.site_id, q.original_quote_id, q.version,
  q.contract_name, q.quote_date, q.contract_start_date,
  q.contract_duration_months, q.shifts_per_day, q.margin_pct,
  q.status, q.valid_until, q.notes,
  q.owner_id, q.created_by, q.created_at, q.updated_at,
  d.name        AS deal_name,
  o.id          AS organisation_id,
  o.name        AS organisation_name,
  s.name        AS site_name
FROM quote_quotes q
JOIN deals d            ON d.id = q.deal_id
JOIN organisations o    ON o.id = d.org_id
LEFT JOIN quote_sites s ON s.id = q.site_id;

CREATE OR REPLACE VIEW v_quote_posts_full AS
SELECT
  p.*,
  g.code AS grade_code, g.description AS grade_description,
  a.code AS area_code,  a.description AS area_description
FROM quote_posts p
LEFT JOIN quote_grades g ON g.id = p.grade_id
LEFT JOIN quote_areas  a ON a.id = p.area_id;

-- ── 7. PERMISSIONS ────────────────────────────────────────────────────

INSERT INTO permissions (name, description)
VALUES
  ('create_quote',     'Create and edit quotes in the Proposal Builder'),
  ('view_all_quotes',  'View quotes owned by other users (managers)')
ON CONFLICT (name) DO NOTHING;

-- Wire these to the appropriate roles via Focus's existing Role Permissions UI.

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════
-- POST-RUN: no seed data for Phase B (quotes are user-created, not seeded).
-- Optional smoke test: insert one quote against an existing deal, verify
-- the v_quote_quotes_full view shows it with org/site joined correctly.
-- ═══════════════════════════════════════════════════════════════════════

-- ═════════════════════════════════════════════ sql/quote_tool_phase_b2.sql
-- ═══════════════════════════════════════════════════════════════════════
-- Quote Tool — Phase B-2 schema + accessory/training seed (PROPOSAL, NOT EXECUTED)
-- ═══════════════════════════════════════════════════════════════════════
-- Target: Dev (test branch) only. Run AFTER Phase B (quote_tool_phase_b.sql).
--
-- Scope:
--   • quote_accessories         — catalog of required accessories (BPV, baton…)
--   • quote_training_courses    — catalog of training requirements (Induction…)
--   • quote_post_discretionary_allowances  — m2m posts ↔ disc allowances + per-post rate
--   • quote_post_discretionary_incentives  — m2m posts ↔ disc incentives + per-post rate
--   • quote_post_statutory_allowances      — m2m posts ↔ statutory toggles (no rate, lives on master)
--   • quote_post_accessories               — m2m posts ↔ accessories
--   • quote_post_training                  — m2m posts ↔ training
--   • Seed data for both catalogs (from the Xone post-edit screen)
--
-- All m2m junction tables use a composite PK (post_id, ref_id) — natural for
-- "is this toggle on for this post" and de-dups by definition.
--
-- For discretionary allowances/incentives the *rate is per-post* (each post
-- can have a different rand amount for the same allowance type). The catalog
-- only holds the name; the actual rand value lives on the junction.
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. ACCESSORIES CATALOG ───────────────────────────────────────────
-- Equipment/items required at a post (Body armour, batons, comms, etc.).
-- Cost info lives elsewhere (will be in Contract Support Items in a later
-- phase). For now we only need the catalog so the toggle works.

CREATE TABLE quote_accessories (
  id              BIGSERIAL    PRIMARY KEY,
  code            TEXT         NOT NULL UNIQUE,
  name            TEXT         NOT NULL,
  display_order   SMALLINT,
  active          BOOLEAN      NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 2. TRAINING COURSES CATALOG ──────────────────────────────────────

CREATE TABLE quote_training_courses (
  id              BIGSERIAL    PRIMARY KEY,
  code            TEXT         NOT NULL UNIQUE,
  name            TEXT         NOT NULL,
  display_order   SMALLINT,
  active          BOOLEAN      NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 3. POST × DISCRETIONARY ALLOWANCES ───────────────────────────────
-- One row per (post, allowance) the user has set on this post. rate_amount
-- is the rand value for THIS post (can differ from any default).

CREATE TABLE quote_post_discretionary_allowances (
  post_id                    BIGINT       NOT NULL REFERENCES quote_posts(id) ON DELETE CASCADE,
  discretionary_allowance_id BIGINT       NOT NULL REFERENCES quote_discretionary_allowances(id),
  rate_amount                NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, discretionary_allowance_id)
);

-- ── 4. POST × DISCRETIONARY INCENTIVES ───────────────────────────────

CREATE TABLE quote_post_discretionary_incentives (
  post_id                    BIGINT       NOT NULL REFERENCES quote_posts(id) ON DELETE CASCADE,
  discretionary_incentive_id BIGINT       NOT NULL REFERENCES quote_discretionary_incentives(id),
  rate_amount                NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, discretionary_incentive_id)
);

-- ── 5. POST × STATUTORY ALLOWANCES (toggles) ─────────────────────────
-- These are pure toggles — the rate lives on quote_statutory_allowances
-- (rate-card table). Presence of the row = the toggle is ON.

CREATE TABLE quote_post_statutory_allowances (
  post_id                BIGINT       NOT NULL REFERENCES quote_posts(id) ON DELETE CASCADE,
  statutory_allowance_id BIGINT       NOT NULL REFERENCES quote_statutory_allowances(id),
  created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, statutory_allowance_id)
);

-- ── 6. POST × ACCESSORIES (toggles) ──────────────────────────────────

CREATE TABLE quote_post_accessories (
  post_id        BIGINT       NOT NULL REFERENCES quote_posts(id) ON DELETE CASCADE,
  accessory_id   BIGINT       NOT NULL REFERENCES quote_accessories(id),
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, accessory_id)
);

-- ── 7. POST × TRAINING (toggles) ─────────────────────────────────────

CREATE TABLE quote_post_training (
  post_id            BIGINT       NOT NULL REFERENCES quote_posts(id) ON DELETE CASCADE,
  training_course_id BIGINT       NOT NULL REFERENCES quote_training_courses(id),
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, training_course_id)
);

-- ── 8. SEED — ACCESSORIES (from the Xone post-edit screen) ───────────

INSERT INTO quote_accessories (code, name, display_order) VALUES
  ('tazer',                 'Tazer (Electric Paralyzer)',  1),
  ('pepper_spray',          'Pepper Spray',                2),
  ('bullet_proof_vest',     'Bullet Proof Vest',           3),
  ('bodyworn_camera',       'Bodyworn Camera',             4),
  ('extendable_baton',      'Extendable Baton',            5),
  ('rubberized_baton',      'Rubberized Baton',            6),
  ('bullet_trap',           'Bullet Trap',                 7),
  ('site_gun_safe',         'Site Gun Safe',               8),
  ('bodyworn_harness',      'Bodyworn Harness',            9),
  ('torch_zartek',          'Torch/Spotlight - Zartek hand held', 10),
  ('occurrence_book',       'Occurrence Book',            11),
  ('handheld_metal_detector','Handheld Metal Detector',   12),
  ('parabellum_9mm',        '9mm Parabellum',             13),
  ('officer_pocket_book',   'Security Officer Pocket Book',14),
  ('restraints_pouch',      'Restraints & Pouch',         15),
  ('baton',                 'Baton',                      16),
  ('torch_rubberized',      'Torch/Spotlight - Rubberized',17),
  ('umbrella',              'Umbrella',                   18),
  ('non_lethal_paintball',  'Non-Lethal - Paintball Gun', 19),
  ('non_lethal_9mm_pellet', 'Non-Lethal - 9mm Pellet Gun',20)
ON CONFLICT (code) DO NOTHING;

-- ── 9. SEED — TRAINING COURSES (from the Xone post-edit screen) ──────

INSERT INTO quote_training_courses (code, name, display_order) VALUES
  ('induction_all_staff',         'Induction training - All staff',     1),
  ('control_room_operators',      'Control Room Operators',             2),
  ('security_officer_semi_skilled','Security Officer (Semi-skilled)',   3),
  ('supervisors_shift_leaders',   'Supervisors/Shift Leaders',          4),
  ('contract_manager_site_seniors','Contract Manager/Site Seniors',     5),
  ('dog_handler',                 'Dog Handler',                        6),
  ('regulation_21',               'Regulation 21',                      7),
  ('fire_fighting',               'Fire Fighting',                      8),
  ('specialised_training',        'Specialised Training',               9),
  ('armed_response_officers',     'Armed Response Officers',           10),
  ('snake_handling',              'Snake Handling',                    11),
  ('first_aid_1_3',               'First Aid 1-3',                     12)
ON CONFLICT (code) DO NOTHING;

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════
-- Verification:
--
-- SELECT 'accessories', count(*) FROM quote_accessories
-- UNION ALL SELECT 'training_courses', count(*) FROM quote_training_courses
-- UNION ALL SELECT 'post_disc_allowances (0)',  count(*) FROM quote_post_discretionary_allowances
-- UNION ALL SELECT 'post_disc_incentives (0)',  count(*) FROM quote_post_discretionary_incentives
-- UNION ALL SELECT 'post_statutory (0)',        count(*) FROM quote_post_statutory_allowances
-- UNION ALL SELECT 'post_accessories (0)',      count(*) FROM quote_post_accessories
-- UNION ALL SELECT 'post_training (0)',         count(*) FROM quote_post_training;
--
-- Expected: 20 / 12 / 0 / 0 / 0 / 0 / 0
-- ═══════════════════════════════════════════════════════════════════════

-- ═════════════════════════════════════════════ sql/quote_tool_phase_b3.sql
-- ═══════════════════════════════════════════════════════════════════════
-- Quote Tool — Phase B-3 schema (PROPOSAL, NOT EXECUTED)
-- ═══════════════════════════════════════════════════════════════════════
-- Target: Dev (test branch) only. Run AFTER Phase B-2.
--
-- Adds the two catalog tables backing the Standard Posts and Standard
-- Headings admin screens (these were localStorage-only in the prototype).
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

CREATE TABLE quote_standard_post_names (
  id            BIGSERIAL    PRIMARY KEY,
  name          TEXT         NOT NULL UNIQUE,    -- 'Security Officer', 'Supervisor', etc.
  display_order SMALLINT,
  active        BOOLEAN      NOT NULL DEFAULT true,
  created_by    BIGINT       REFERENCES people(id),
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE quote_standard_heading_names (
  id            BIGSERIAL    PRIMARY KEY,
  name          TEXT         NOT NULL UNIQUE,    -- 'Main Gate', 'Response Team', etc.
  display_order SMALLINT,
  active        BOOLEAN      NOT NULL DEFAULT true,
  created_by    BIGINT       REFERENCES people(id),
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Seed (from the prototype defaults)

INSERT INTO quote_standard_post_names (name, display_order) VALUES
  ('Security Officer',          1),
  ('Senior Security Officer',   2),
  ('Supervisor',                3),
  ('Armed Response Officer',    4),
  ('Patrol Officer',            5),
  ('Control Room Operator',     6),
  ('Dog Handler',               7),
  ('Mobile Supervisor',         8),
  ('Site Manager',              9)
ON CONFLICT (name) DO NOTHING;

INSERT INTO quote_standard_heading_names (name, display_order) VALUES
  ('Main Gate',          1),
  ('Side Gate',          2),
  ('Reception',          3),
  ('Weighbridge',        4),
  ('Response Team',      5),
  ('Control Room',       6),
  ('Perimeter Patrol',   7),
  ('Management',         8),
  ('Specialist Posts',   9)
ON CONFLICT (name) DO NOTHING;

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════
-- Verification:
-- SELECT 'standard_posts',    count(*) FROM quote_standard_post_names
-- UNION ALL SELECT 'standard_headings', count(*) FROM quote_standard_heading_names;
-- Expected: 9 / 9
-- ═══════════════════════════════════════════════════════════════════════

-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  PART 3 — VERIFICATION  (all should report 'ok' / expected counts)     ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
SELECT 'branches table'        AS check, CASE WHEN to_regclass('public.branches')             IS NOT NULL THEN 'ok' ELSE 'MISSING' END AS result
UNION ALL SELECT 'system_user_branches',  CASE WHEN to_regclass('public.system_user_branches')  IS NOT NULL THEN 'ok' ELSE 'MISSING' END
UNION ALL SELECT 'campaign_targets',       CASE WHEN to_regclass('public.campaign_targets')      IS NOT NULL THEN 'ok' ELSE 'MISSING' END
UNION ALL SELECT 'campaign_cadence_steps', CASE WHEN to_regclass('public.campaign_cadence_steps')IS NOT NULL THEN 'ok' ELSE 'MISSING' END
UNION ALL SELECT 'quote_quotes',           CASE WHEN to_regclass('public.quote_quotes')          IS NOT NULL THEN 'ok' ELSE 'MISSING' END
UNION ALL SELECT 'deals.branch_id',        CASE WHEN EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='deals' AND column_name='branch_id') THEN 'ok' ELSE 'MISSING' END
UNION ALL SELECT 'leads.cadence_started_at',CASE WHEN EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='leads' AND column_name='cadence_started_at') THEN 'ok' ELSE 'MISSING' END
UNION ALL SELECT 'lead_sources.is_system', CASE WHEN EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='lead_sources' AND column_name='is_system') THEN 'ok' ELSE 'MISSING' END;

-- Quote seed sanity (expect: 16 salary, 32 statutory, 20 accessories, 12 training, 9 std posts):
SELECT 'salary_rates' AS seed, count(*) FROM quote_salary_rates
UNION ALL SELECT 'statutory_allowances', count(*) FROM quote_statutory_allowances
UNION ALL SELECT 'accessories',          count(*) FROM quote_accessories
UNION ALL SELECT 'training_courses',     count(*) FROM quote_training_courses
UNION ALL SELECT 'standard_post_names',  count(*) FROM quote_standard_post_names;
